
" Vundle init.
set nocompatible
filetype off
set rtp+=~/.vim/bootstrap

" Vundle plugins.
call vundle#begin()
Plugin 'bling/vim-airline' " status bar
Plugin 'kien/ctrlp.vim' " let's get fuzzy!
Plugin 'mxw/vim-jsx' " depends on vim-javascript
Plugin 'pangloss/vim-javascript' " javascript syntax
Plugin 'tpope/vim-fugitive' " git wrapper
Plugin 'tpope/vim-repeat' " ability to repeat plugin actions
Plugin 'tpope/vim-surround' " surround things
Plugin 'tpope/vim-unimpaired' " some simple pair mappings
Plugin 'lilydjwg/colorizer' " color definition highlighting
call vundle#end()

" Colors!
set t_ut=
set t_Co=256
colorscheme aurora

" Airline.
set laststatus=2
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme = 'powerlineish'
let g:airline#extensions#tabline#enabled = 1

" Remap leader.
let mapleader=" "

" Remove escape delay.
set timeoutlen=1000 ttimeoutlen=0

" Enable syntax.
syntax enable

" Clipboard
if $TMUX == ''
	set clipboard=unnamedplus
endif

" Enable mouse.
set mouse=a

" Enable line numbers.
set number

" Highlight line end.
set cursorline
if version >= 703
	set colorcolumn=100
endif

" Highlight current line only on focused window.
set cursorline
autocmd WinEnter * setlocal cursorline
autocmd BufEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
autocmd BufLeave * setlocal nocursorline

" Tab completion.
set wildmode=longest,list,full
set wildmenu

" Indentation.
filetype plugin indent on
set expandtab
set tabstop=4
set shiftwidth=4
nmap <S-Tab> <<
imap <S-Tab> <Esc><<i

" Fix backspace.
set backspace=indent,eol,start

" Fix PGUP/PGDN.
map <silent> <PageUp> 1000<C-U>
map <silent> <PageDown> 1000<C-D>
imap <silent> <PageUp> <C-O>1000<C-U>
imap <silent> <PageDown> <C-O>1000<C-D>
set nostartofline

" JSX.
let g:jsx_ext_required = 0

" Trailing whitespace.
match ErrorMsg '\s\+$'
nnoremap <Leader>rtw :%s/\s\+$//e<CR>

" Buffer/tab mappings.
nnoremap gb :bnext<CR>
nnoremap gB :bprevious<CR>
nnoremap gd :bdelete<CR>
nnoremap gD :tabclose<CR>

" Versions of cc and o that don't exit normal mode
nmap <leader>cc cc<ESC>
nmap <leader>o o<ESC>
nmap <leader>O O<ESC>

" Sudo save shortcut.
cmap w!! w !sudo tee > /dev/null %

" Load machine-specific stuff.
if filereadable(expand("$HOME/.vimrc.loc"))
    source $HOME/.vimrc.loc
endif

