
" vundle init
set nocompatible
filetype off
set rtp+=~/.vim/bootstrap

" set opengl shader language file types
let g:glsl_file_extensions = '*.glsl,*.geom,*.vert,*.frag,*.gsh,*.vsh,*.fsh,*.vs,*.fs,*.gs,*.tcs,*.tes'

" vundle plugins
call vundle#begin()
Plugin 'sheerun/vim-polyglot' " syntax highlighting for many languages
Plugin 'scrooloose/nerdcommenter' " commenting
Plugin 'tpope/vim-fugitive' " git wrapper
Plugin 'tpope/vim-repeat' " ability to repeat plugin actions
Plugin 'tpope/vim-surround' " surround things
Plugin 'tpope/vim-unimpaired' " some simple pair mappings
Plugin 'vim-scripts/cscope.vim'
call vundle#end()

" remap leader
let mapleader=" "

" encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

" colors!
set t_ut=
set t_Co=256
colorscheme aurora

" toggle colorscheme
fun! ToggleColorScheme()
    if "aurora" ==? g:colors_name
        colorscheme industry
    else
        colorscheme aurora
    endif
endfun
nnoremap <Leader>c :call ToggleColorScheme()<CR>

" airline
set laststatus=2
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme = 'powerlineish'
let g:airline#extensions#tabline#enabled = 1

" remove escape delay
set timeoutlen=1000 ttimeoutlen=0

" enable syntax
syntax enable

" clipboard
if $TMUX == ''
	set clipboard+=unnamed
endif

" enable mouse
set mouse=a

" line numbers
set nonumber
nmap <Leader>l :setlocal number!<CR>

" highlight line end
if version >= 703
	set colorcolumn=
    " Toggle column guide
    fun! ToggleColorColumn()
        if empty(&colorcolumn)
            setlocal colorcolumn=80
        else
            setlocal colorcolumn=
        endif
    endfun
    nnoremap <Leader>\ :call ToggleColorColumn()<CR>
endif

" line wrap
set textwidth=80

" tab completion
set wildmode=longest,list,full
set wildmenu

" indentation
filetype plugin indent on
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
nmap <S-Tab> <<
imap <S-Tab> <Esc><<i

" fix backspace
set backspace=indent,eol,start

" fix PGUP/PGDN
map <silent> <PageUp> 1000<C-U>
map <silent> <PageDown> 1000<C-D>
imap <silent> <PageUp> <C-O>1000<C-U>
imap <silent> <PageDown> <C-O>1000<C-D>
set nostartofline

" trailing whitespace
match ErrorMsg '\s\+$'
nnoremap <Leader>rtw :%s/\s\+$//e<CR>

" buffer mappings.
nnoremap <Leader>b :buffer 
nnoremap <Leader>n :bnext<CR>
nnoremap <Leader>p :bprevious<CR>
nnoremap <Leader><Tab> :e#<CR>
nnoremap <Leader>z :split<CR>
nnoremap <Leader>x :vsplit<CR>

" sort visual
vnoremap <Leader>s :sort<CR>

" steal hbw's line centering mappings
fun! ScrollToPercent(percent)
    let movelines=winheight(0)*(50-a:percent)/100
    echo movelines
    if movelines<0
        let motion='k'
        let rmotion='j'
        let movelines=-movelines
    elseif movelines>0
        let motion='j'
        let rmotion='k'
    else
        return 0
    endif
    if has('float') && type(movelines)==type(0.0)
        let movelines=float2nr(movelines)
    endif
    execute 'normal! zz'.movelines.motion.'zz'.movelines.rmotion
endfun

map zr :call ScrollToPercent(25)<CR>
map zv :call ScrollToPercent(75)<CR>

" configure search
set incsearch " jump while entering query
set hlsearch
set ignorecase
set smartcase
nnoremap <Leader>h :noh<CR>

" completion settings (:help ins-completion)
set complete+=i " scan current and included files
set complete+=d " scan current and included files for defined name or macro

" toggle paste-mode
nnoremap <Leader>v :set paste!<CR>

" uncomment US in pacman mirrorlist.
fun! UncommentMirrorList()
    exec "silent! normal! /United States\<CR>jV/\\n\\n\<CR>:s/\#//g\<CR>:wq\<CR>"
endfun

" sudo save shortcut
cmap w!! w !sudo tee > /dev/null %

" load machine-specific stuff
if filereadable(expand("$HOME/.vimrc.loc"))
    source $HOME/.vimrc.loc
endif

