#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

. $HOME/.xvars
if [ -e $HOME/.xvars.loc ]; then
    . $HOME/.xvars.loc
fi

# capslock -> esc
setxkbmap -option caps:escape

# swap alt/meta keys
if $DOTFILES_VAR_SWAP_SUPER && [ -e $HOME/.Xmodmap ]; then
    xmodmap $HOME/.Xmodmap
fi

hash xbindkeys 2> /dev/null
if [ $? -eq 0 ]; then
    xbindkeys &
fi

xrdb -merge $HOME/.Xresources
if [ -e $HOME/.Xresources.loc ]; then
    xrdb -merge $HOME/.Xresources.loc &
fi

# disable mouse acceleration
xset m 0 0 &

# set key repeat rate
xset r rate 220 50 &

if [ $(hostname) != "arthur" ]; then
    hash compton 2> /dev/null
    if [ $? -eq 0 ]; then
        pidof compton > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            compton &
        fi
    fi
fi

hash xflux 2> /dev/null
if [ $? -eq 0 ]; then
    pidof xflux > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        xflux -z 98105 -k 3800 &
    fi
fi

# load machine-specific stuff
if [ -e $HOME/.xinitrc.loc ]; then
    . $HOME/.xinitrc.loc
fi

# desktop background
if [ -e $HOME/.fehbg ]; then
    sh $HOME/.fehbg &
fi

hash nvidia-settings 2> /dev/null
if [ $? -eq 0 -a -e $HOME/.nvidia-settings-rc ]; then
    nvidia-settings --load-config-only
fi

if [ -e "$HOME/.display-brightness.dat" ]; then
    display-brightness-commit $(cat "$HOME/.display-brightness.dat")
fi

if [ $(hostname) = "zaphod" ]; then
    exec startxfce4
elif [ -e $HOME/.i3/config.loc ]; then
    exec i3 -c $HOME/.i3/config.loc -V >> $HOME/.i3/i3log 2>&1
else
    exec i3 -c $HOME/.i3/config -V >> $HOME/.i3/i3log 2>&1
fi

