#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Disable caps lock to control.
setxkbmap -option ctrl:nocaps

# Swap Alt/Meta keys.
if [ -e $HOME/.Xmodmap ]; then
    xmodmap $HOME/.Xmodmap
fi

# Bind custom keys.
hash xbindkeys 2> /dev/null
if [ $? -eq 0 ]; then
    xbindkeys &
fi

# Load .Xresources.
xrdb -merge $HOME/.Xresources &

# Adjust mouse sensitivity/acceleration.
xset m 1 10 &
xset r rate 220 40 &

# Set background.
sh $HOME/.fehbg &

# Start compton.
hash compton 2> /dev/null
if [ $? -eq 0 ]; then
    pidof compton >& /dev/null
    if [ $? -ne 0 ]; then
        compton &
    fi
fi

# Start flux.
hash xflux 2> /dev/null
if [ $? -eq 0 ]; then
    pidof xflux >& /dev/null
    if [ $? -ne 0 ]; then
        xflux -z 98105 -k 4100 &
    fi
fi

# Start mpdscribble. TODO: Move to systemd --user
hash mpdscribble 2> /dev/null
if [ $? -eq 0 ]; then
    pidof mpdscribble >& /dev/null
    if [ $? -ne 0 ]; then
        mpdscribble &
    fi
fi

# Load machine-specific stuff.
if [ -e $HOME/.xinitrc.loc ]; then
    source $HOME/.xinitrc.loc
fi

exec i3 -V >> $HOME/.i3/i3log 2>&1

