#!/bin/sh

PATH=$PATH:$DOTFILES/bin

if [ -z "$TMUX" ]; then
    ulimit -c unlimited

    export DOTFILES=$HOME/dot
    export HISTFILE=$HOME/.histfile
    export VISUAL=vi
    hash vim 2> /dev/null
    if [ 0 == $? ]; then
        VISUAL=vim
    fi
    hash nvim 2> /dev/null
    if [ 0 == $? ]; then
        VISUAL=nvim
    fi
    export EDITOR=$VISUAL
    if [ "$(hostname)" != "ford" ]; then
        export MPD_HOST=/tmp/mpd.sock
    fi
fi

# Load Linux stuff.
if [ -e $HOME/.profile.linux ]; then
    source $HOME/.profile.linux
fi

# Load OS X stuff.
if [ -e $HOME/.profile.osx ]; then
    source $HOME/.profile.osx
fi

# Load machine-specific stuff.
if [ -e $HOME/.profile.loc ]; then
    source $HOME/.profile.loc
fi

