#!/bin/sh

PATH=$PATH:$DOTFILES/bin

if [ -z "$TMUX" ]; then
    ulimit -c unlimited
fi

export DOTFILES="$HOME/dot"
export DOTFILES_LOCAL="$HOME/dot.local"

# Override these defaults in ~/.profile.loc
export DOTFILES_VAR_SWAP_SUPER=false

export HISTFILE="$HOME/.histfile"
export VISUAL=vi
hash vim 2> /dev/null
if [ "$?" -eq 0 ]; then
    VISUAL=vim
fi
hash nvim 2> /dev/null
if [ "$?" -eq 0 ]; then
    VISUAL=nvim
fi
export EDITOR=$VISUAL
if [ "$(hostname)" != "ford" ]; then
    export MPD_HOST=/tmp/mpd.sock
fi

if [ -e $HOME/.profile.freebsd ]; then
    source $HOME/.profile.freebsd
fi
if [ -e $HOME/.profile.linux ]; then
    source $HOME/.profile.linux
fi
if [ -e $HOME/.profile.osx ]; then
    source $HOME/.profile.osx
fi
if [ -e $HOME/.profile.loc ]; then
    source $HOME/.profile.loc
fi

